#!/usr/bin/env bash
# ZebraCode Hook: File protection
# Trigger: PreToolUse (Edit|Write)
# Purpose: Block edits to protected files (.env, lock files, migrations)
# Exit 2 = block, Exit 0 = allow

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')
CWD=$(echo "$INPUT" | jq -r '.cwd // empty')

# No file path = allow
[[ -z "$FILE_PATH" ]] && exit 0

# Validate path: must be absolute, reject path traversal attempts
[[ "$FILE_PATH" != /* ]] && exit 0
[[ "$FILE_PATH" == *".."* ]] && exit 0

# Resolve to basename and relative path for pattern matching
BASENAME=$(basename "$FILE_PATH")
# Make path relative to CWD for pattern matching
REL_PATH="$FILE_PATH"
if [[ -n "$CWD" && "$FILE_PATH" == "$CWD"* ]]; then
  REL_PATH="${FILE_PATH#"$CWD"/}"
fi

# Try to read protected patterns from z-project-config.yml
CONFIG_FILE=""
if [[ -n "$CWD" && -f "$CWD/.claude/z-project-config.yml" ]]; then
  CONFIG_FILE="$CWD/.claude/z-project-config.yml"
fi

# Default protected patterns (used if no config exists)
DEFAULT_PATTERNS=(
  ".env*"
  "package-lock.json"
  "composer.lock"
  "yarn.lock"
  "pnpm-lock.yaml"
)

# Build pattern list from config or defaults
PATTERNS=()
if [[ -n "$CONFIG_FILE" ]]; then
  # Read patterns from YAML config
  while IFS= read -r pattern; do
    [[ -n "$pattern" && "$pattern" != "null" ]] && PATTERNS+=("$pattern")
  done < <(grep -A 100 '^protected_files:' "$CONFIG_FILE" \
    | tail -n +2 \
    | grep '^\s*-\s*' \
    | sed 's/^\s*-\s*//; s/"//g; s/'"'"'//g; s/\s*#.*//' \
    | while read -r line; do [[ -n "$line" ]] && echo "$line"; done)
fi

# Use defaults if no patterns from config
if [[ ${#PATTERNS[@]} -eq 0 ]]; then
  PATTERNS=("${DEFAULT_PATTERNS[@]}")
fi

# Check file against protected patterns
REASON=""
for pattern in "${PATTERNS[@]}"; do
  case "$pattern" in
    .env*)
      # Match .env, .env.local, .env.production, etc.
      if [[ "$BASENAME" == .env* ]]; then
        REASON="Environment files contain secrets and should not be edited by AI."
        break
      fi
      ;;
    *-lock.json|*.lock|*-lock.yaml)
      # Lock files
      if [[ "$BASENAME" == "$pattern" ]]; then
        REASON="Lock files should be generated by package managers, not edited directly."
        break
      fi
      ;;
    database/migrations/*|*/migrations/*)
      # Migration files
      if [[ "$REL_PATH" == database/migrations/* || "$REL_PATH" == */migrations/* ]]; then
        REASON="Existing migrations should not be modified. Create a new migration instead."
        break
      fi
      ;;
    *)
      # Generic glob matching
      if [[ "$BASENAME" == $pattern || "$REL_PATH" == $pattern ]]; then
        REASON="Protected file: ${BASENAME}. Editing blocked by ZebraCode hook."
        break
      fi
      ;;
  esac
done

if [[ -n "$REASON" ]]; then
  # Block the edit
  cat <<EOF
{
  "hookSpecificOutput": {
    "hookEventName": "PreToolUse",
    "permissionDecision": "deny",
    "permissionDecisionReason": "$REASON"
  }
}
EOF
  exit 2
fi

exit 0
